services:
  app:
    build:
      context: .
      target: dev
    working_dir: /extension
    command: "uv run swoext run"
    volumes:
      - .:/extension
    env_file:
      - .env
    ports:
      - "8080:8080"

  jaeger:
    image: jaegertracing/jaeger:2.17.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"
