version: '3'

services:
  app:
    container_name: adobe_vipm
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: bash -c "poetry install --only-root && swoext run"
    volumes: 
      - .:/extension
    environment:
      - EXT_ADOBE_CONFIG_FILE=/extension/adobe_vipm/adobe_config.json
      - EXT_QUERYING_TEMPLATE_ID=TPL-1234-5678
      - EXT_COMPLETED_TEMPLATE_ID=TPL-3333-4444
      - MPT_API_BASE_URL=http://devmock:8000
    depends_on:
      - devmock

  devmock:
    container_name: adobe_vipm_devmock
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: uvicorn --host 0.0.0.0 devmock.app:app
    volumes: 
      - .:/extension
    environment:
      - EXT_ADOBE_CONFIG_FILE=/extension/adobe_vipm/adobe_config.json
      - EXT_QUERYING_TEMPLATE_ID=TPL-1234-5678
      - EXT_COMPLETED_TEMPLATE_ID=TPL-3333-4444

  bash:
    container_name: adobe_vipm_bash
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    environment:
      - EXT_ADOBE_CONFIG_FILE=/extension/adobe_vipm/adobe_config.json
      - EXT_QUERYING_TEMPLATE_ID=TPL-1234-5678
      - EXT_COMPLETED_TEMPLATE_ID=TPL-3333-4444

  app_test:
    container_name: adobe_vipm_test
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "flake8 . && pytest"
    volumes:
      - .:/extension
    environment:
      - EXT_ADOBE_CONFIG_FILE=/extension/adobe_vipm/adobe_config.json
      - EXT_QUERYING_TEMPLATE_ID=TPL-1234-5678
      - EXT_COMPLETED_TEMPLATE_ID=TPL-3333-4444

  format:
    container_name: adobe_vipm_format
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "isort . && black ."
    volumes:
      - .:/extension
    environment:
      - EXT_ADOBE_CONFIG_FILE=/extension/adobe_vipm/adobe_config.json
      - EXT_QUERYING_TEMPLATE_ID=TPL-1234-5678
      - EXT_COMPLETED_TEMPLATE_ID=TPL-3333-4444
