version: '3'

services:
  app:
    container_name: adobe_vipm
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: swoext run --no-color
    volumes: 
      - .:/extension
    env_file:
      - .env
    depends_on:
      - devmock

  devmock:
    container_name: adobe_vipm_devmock
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: uvicorn --host 0.0.0.0 devmock.app:app
    volumes: 
      - .:/extension
    env_file:
      - .env

  bash:
    container_name: adobe_vipm_bash
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .env

  app_test:
    container_name: adobe_vipm_test
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "ruff check . && pytest"
    volumes:
      - .:/extension
    env_file:
      - .env

  format:
    container_name: adobe_vipm_format
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "ruff check . --select I --fix && ruff format ."
    volumes:
      - .:/extension
    env_file:
      - .env
