version: '3'

services:
  app:
    container_name: adobe_vipm
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: bash -c "poetry install --only-root && swoext run --no-color"
    volumes: 
      - .:/extension
    env_file:
      - .env
    environment:
      - MPT_API_BASE_URL=http://devmock:8000
    depends_on:
      - devmock

  devmock:
    container_name: adobe_vipm_devmock
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: uvicorn --host 0.0.0.0 devmock.app:app
    volumes: 
      - .:/extension
    env_file:
      - .env

  bash:
    container_name: adobe_vipm_bash
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .env

  app_test:
    container_name: adobe_vipm_test
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "flake8 . && poetry install && pytest"
    volumes:
      - .:/extension
    env_file:
      - .env

  format:
    container_name: adobe_vipm_format
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "isort . && black ."
    volumes:
      - .:/extension
    env_file:
      - .env
