version: 1.0.0
openapi: /bypass/openapi.json

#schedules:
#  - path: /api/v1/cron/dojob
#    id: my.cron.job
#    name: "My cron job"
#    description: "Test cron job"
#    cron: "* * * * *"
#deferrables:
#  - path: "/api/v1/tasks/synchronize"
#    method: GET
#    description: "Run a background synchronization task"
events:
  - event: platform.commerce.order.created
    condition: "eq(product.id,PRD-5516-5707)"
    path: "/api/v2/events/orders/purchase"
    task: true
  - event: platform.commerce.order.status_changed
    condition: "and(eq(status,Processing),eq(product.id,PRD-5516-5707))"
    path: "/api/v2/events/orders/change"
    task: false
#plugs:
#  - id: subs-actions
#    name: Subscriptions Actions Demo
#    description: Check sockets
#    icon: adobe.png
#    socket: portal.commerce.subscriptions.actions
#    href: "/static/index.js"
#webhooks:
#  - type: validationPurchaseOrderDraft
#    description: "Validate purchase order draft"
#    path: /api/v1/validation/orders
#    criteria:
#      product.id: "{{ settings.product_id }}"
