STATUS_PROCESSED = "1000"
STATUS_PENDING = "1002"
STATUS_GENERIC_FAILURE = "1004"
STATUS_ORDER_CANCELLED = "1008"
STATUS_ORDER_INACTIVE_DISTRIBUTOR = "1020"
STATUS_ORDER_INACTIVE_RESELLER = "1022"
STATUS_ORDER_INACTIVE_CUSTOMER = "1024"
STATUS_ORDER_INVALID_CUSTOMER_ID = "1026"

ORDER_STATUS_DESCRIPTION = {
    STATUS_GENERIC_FAILURE: "Inactive account, failed order or inactive subscription.",
    STATUS_ORDER_CANCELLED: "Order has been cancelled.",
    STATUS_ORDER_INACTIVE_DISTRIBUTOR: "Distributor is inactive.",
    STATUS_ORDER_INACTIVE_RESELLER: "Reseller is inactive.",
    STATUS_ORDER_INACTIVE_CUSTOMER: "Customer is inactive.",
    STATUS_ORDER_INVALID_CUSTOMER_ID: "The provided customer identifier is invalid.",
}

UNRECOVERABLE_ORDER_STATUSES = list(ORDER_STATUS_DESCRIPTION.keys())
