ORDER_TYPE_PURCHASE = "purchase"
ORDER_TYPE_CHANGE = "change"
ORDER_TYPE_TERMINATION = "termination"

PARAM_ADDRESS = "address"
PARAM_COMPANY_NAME = "companyName"
PARAM_CONTACT = "contact"
PARAM_CUSTOMER_ID = "customerId"
PARAM_MEMBERSHIP_ID = "membershipId"
PARAM_PREFERRED_LANGUAGE = "preferredLanguage"
PARAM_RETRY_COUNT = "retryCount"
PARAM_SUBSCRIPTION_ID = "subscriptionId"

CANCELLATION_WINDOW_DAYS = 14
