from enum import StrEnum

import regex as re


class AdobeStatus(StrEnum):
    STATUS_PROCESSED = "1000"
    STATUS_PENDING = "1002"
    STATUS_INACTIVE_OR_GENERIC_FAILURE = "1004"
    STATUS_ORDER_CANCELLED = "1008"
    STATUS_ORDER_INACTIVE_DISTRIBUTOR = "1020"
    STATUS_ORDER_INACTIVE_RESELLER = "1022"
    STATUS_ORDER_INACTIVE_CUSTOMER = "1024"
    STATUS_ORDER_INVALID_CUSTOMER_ID = "1026"
    STATUS_INVALID_FIELDS = "1117"
    STATUS_INVALID_ADDRESS = "1118"
    STATUS_INVALID_MINIMUM_QUANTITY = "1135"
    STATUS_ACCOUNT_ALREADY_EXISTS = "1127"
    STATUS_TRANSFER_INVALID_MEMBERSHIP = "5115"
    STATUS_TRANSFER_INVALID_MEMBERSHIP_OR_TRANSFER_IDS = "5116"
    STATUS_TRANSFER_INELIGIBLE = "5117"
    STATUS_TRANSFER_ALREADY_TRANSFERRED = "5118"
    STATUS_TRANSFER_INACTIVE_RESELLER = "5119"
    STATUS_TRANSFER_NO_ADMIN_CONTACTS = "5120"
    STATUS_TRANSFER_IN_PROGRESS = "5121"
    STATUS_TRANSFER_INACTIVE_ACCOUNT = "1010"
    STATUS_SUBSCRIPTION_INACTIVE = "3119"
    STATUS_INVALID_RENEWAL_STATE = "3120"
    STATUS_LINE_ITEM_OFFER_ID_EXPIRED = "3123"
    STATUS_INTERNAL_SERVER_ERROR = "1124"
    STATUS_GC_DEPLOYMENT_ACTIVE = "1000"
    STATUS_SUBSCRIPTION_TERMINATED = "1004"
    STATUS_SUBSCRIPTION_ACTIVE = "1000"


ORDER_STATUS_DESCRIPTION = {
    AdobeStatus.STATUS_INACTIVE_OR_GENERIC_FAILURE: "Inactive account, failed order or inactive "
    "subscription.",
    AdobeStatus.STATUS_ORDER_CANCELLED: "Order has been cancelled.",
    AdobeStatus.STATUS_ORDER_INACTIVE_DISTRIBUTOR: "Distributor is inactive.",
    AdobeStatus.STATUS_ORDER_INACTIVE_RESELLER: "Reseller is inactive.",
    AdobeStatus.STATUS_ORDER_INACTIVE_CUSTOMER: "Customer is inactive.",
    AdobeStatus.STATUS_ORDER_INVALID_CUSTOMER_ID: "The provided customer identifier is invalid.",
}

SUBSCRIPTION_STATUS_DESCRIPTION = {
    AdobeStatus.STATUS_SUBSCRIPTION_TERMINATED: "Subscription is terminated.",
}

UNRECOVERABLE_ORDER_STATUSES = list(ORDER_STATUS_DESCRIPTION.keys())

UNRECOVERABLE_TRANSFER_STATUSES = [
    AdobeStatus.STATUS_TRANSFER_INELIGIBLE,
    AdobeStatus.STATUS_TRANSFER_ALREADY_TRANSFERRED,
    AdobeStatus.STATUS_TRANSFER_INACTIVE_RESELLER,
    AdobeStatus.STATUS_TRANSFER_NO_ADMIN_CONTACTS,
    AdobeStatus.STATUS_TRANSFER_IN_PROGRESS,
]

ORDER_TYPE_NEW = "NEW"
ORDER_TYPE_PREVIEW = "PREVIEW"
ORDER_TYPE_PREVIEW_RENEWAL = "PREVIEW_RENEWAL"
ORDER_TYPE_RENEWAL = "RENEWAL"
ORDER_TYPE_RETURN = "RETURN"


MINLEN_COMPANY_NAME = 4
MINLEN_NAME = 1
MAXLEN_POSTAL_CODE = 40
MAXLEN_CITY = 40
MAXLEN_ADDRESS_LINE_1 = 60
MAXLEN_ADDRESS_LINE_2 = 60
MAXLEN_PHONE_NUMBER = 40
MAXLEN_COMPANY_NAME = 59
MAXLEN_NAME = 35
MINQTY_LICENSES = 10
MINQTY_CONSUMABLES = 1000

REGEX_COMPANY_NAME = re.compile(r"^[\w ,.＆&・\'()（）\\\"/-]*$")
REGEX_FIRST_LAST_NAME = re.compile(r"^[\w ,.＆&'\\\"]*$")
REGEX_EMAIL = re.compile(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$")
REGEX_SANITIZE_COMPANY_NAME = re.compile(r"[^\w ,.＆&・\'()（）\\\"/-]")
REGEX_SANITIZE_FIRST_LAST_NAME = re.compile(r"[^\p{L} 0-9,.＆&' \-\\\"]")


class ThreeYearCommitmentStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    COMMITTED = "COMMITTED"
    ACTIVE = "ACTIVE"
    REQUESTED = "REQUESTED"
    NONCOMPLIANT = "NONCOMPLIANT"
    EXPIRED = "EXPIRED"


THREE_YC_TEMP_3YC_STATUSES = (
    ThreeYearCommitmentStatus.REQUESTED,
    ThreeYearCommitmentStatus.ACCEPTED,
)


class OfferType(StrEnum):
    LICENSE = "LICENSE"
    CONSUMABLES = "CONSUMABLES"


CANCELLATION_WINDOW_DAYS = 14
