MARKET_SEGMENT_COMMERCIAL = "COM"
MARKET_SEGMENT_EDUCATION = "EDU"
MARKET_SEGMENT_GOVERNMENT = "GOV"
MARKET_SEGMENT_LARGE_GOVERNMENT_AGENCY = "GOV_LGA"

MARKET_SEGMENTS = {
    MARKET_SEGMENT_COMMERCIAL: "COM",
    MARKET_SEGMENT_GOVERNMENT: "GOV",
    MARKET_SEGMENT_EDUCATION: "EDU",
    MARKET_SEGMENT_LARGE_GOVERNMENT_AGENCY: "GOV",
}

MARKET_SEGMENT_TO_AIRTABLE_SEGMENT = {
    MARKET_SEGMENT_COMMERCIAL: "Commercial",
    MARKET_SEGMENT_GOVERNMENT: "Government",
    MARKET_SEGMENT_EDUCATION: "Education",
    MARKET_SEGMENT_LARGE_GOVERNMENT_AGENCY: "LargeGovernment",
}
