name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  danger:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Danger
        uses: softwareone-platform/one-danger@1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
