name: SWO Marketplace Extension PR build

on:
  pull_request:
    branches: [ "main", "release/**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build test containers
      run: docker-compose build app_test

    - name: Run validation & test
      run: docker-compose run --service-ports app_test
  
    - name: Stop containers
      if: always()
      run: docker-compose down
