name: SWO Marketplace Extension PR build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        with:
          fetch-depth: 0

    - name: Build test containers
      run: docker-compose build app_test

    - name: Run validation & test
      run: docker-compose run --service-ports app_test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
    - name: Stop containers
      if: always()
      run: docker-compose down
